org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,MULTIDEX_NOT_NEEDED,JAVA_COMPILE_DEPRECATED_SOURCE_TARGET
